---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары по цене, категории, бренду
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность добавлять товар в корзину и продолжить выбирать товары в каталоге
  - На странице корзины пользователь должен иметь возможность удалить товар из корзины и продолжить выбирать товары в каталоге
  - Пользователь должен иметь возможность оформить заказ с переходом на страницу оплаты
  - Сайт должен иметь мобильную версию
  
non-functional:
  - Корзина хранится в сессии браузера
  - Сайт должен быть адаптирован под различные устройства
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть разработан с учетом удобства использования и быть оптимизирован для скорости работы
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
  
implicit:
  - Пользователь должен иметь возможность отменить выбранную ранее категорию
  - Протокол HTTPS
  - В поле фильтра по цене должна быть указана валюта и стоимость самого дорогого товара в каталоге
  - В фильтр товаров по цене нельзя вводить отрицательные значения
  - У пользователя не должно быть доступа к чужим корзинам
  - На странице товара и в каталоге должны быть указаны название товара, рейтинг, цена со скидкой и без нее
  - Для поля поиска должен применяться полнотектовый поиск
  - На сайте есть кнопки переключения страниц каталого товара (Предыдущая/Следующая)
  - В карточке товара пользователь должен иметь возможность просмартривать все фотографии товара в крупном виде
  - Фото товаров в превью должны корректно отображаться, масштабироваться для превью
  - В карточке товара и в каталоге должно быть отмечено, в каком количестве товар уже был добавлен в корзину
  - Наименования категорий должны быть на том же языке, который выбран для сайта
  - На сайте должна быть реализована форма регистрации
  - Оформить заказ может только зарегестрированный пользователь с контактными данными
