---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову и категории
  - Пользователь должен иметь возможность фильтровать товары по цене, категории, бренду
  - Пользователь должен иметь возможность переходить на карточку с описанием товара из каталога и из корзины
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность добавлять товары в корзину и продолжить выбирать товары в каталоге
  - На странице корзины пользователь должен иметь возможность удалить товар из корзины и продолжить выбирать товары в каталоге
  - Пользователь должен иметь возможность очистить корзину нажатием на кнопку "Clear Cart" (“Очистить корзину”)
  - Пользователь должен иметь возможность оформить заказ с переходом на страницу оплаты
  - Сайт должен иметь мобильную версию

  
non-functional:
  - Корзина хранится в сессии браузера
  - Сайт должен быть адаптирован под различные устройства
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть разработан с учетом удобства использования 
  - Сайт должен быть оптимизирован для медленного интернет-соединения
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика

  
implicit:
  - Пользователь должен иметь возможность отменить выбранную ранее категорию
  - Протокол HTTPS
  - В поле фильтра по цене должна быть указана валюта и стоимость самого дорогого товара в каталоге
  - В фильтр товаров по цене нельзя вводить отрицательные значения
  - При вводе ключевого слова, которому не соответствует ни один товар, появляется сообщение "Nothing found!" (“Ничего не найдено!”)
  - У пользователя не должно быть доступа к чужим корзинам
  - На странице товара и в каталоге должны быть указаны название товара, рейтинг, цена со скидкой и без нее
  - При добавлении или удалении товаров происходит пересчет суммы и количества товаров в корзине
  - Для поля поиска должен применяться полнотекстовый поиск
  - На сайте есть кнопки переключения страниц каталога товара (Предыдущая/Следующая)
  - В карточке товара пользователь должен иметь возможность просматривать все фотографии товара в крупном виде
  - Фото товаров в превью должны корректно отображаться, масштабироваться для превью
  - В карточке товара и в каталоге отмечено, что данный товар уже был добавлен в корзину
  - Сайт должен корректно переводиться на английский и русский язык
  - Выбранный язык сайта при обновлении страницы не должен меняться

