---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт должен иметь мобильную версию
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - сообщение, что ничего не найдено по данному запросу
  
  - SPA-приложение  которое не перезагружает страницу.
  - На странице товара и в каталоге нужно выводить название, рейтинг, цена со скидкой и без нее.
    Пользователь будет добавлять товар в корзину и продолжать выбирать товары в каталоге.
  - фильтр "в наличии" (если убрать галочку в наличии, то )
  - вопрос "уверены, что хотите очистить корзину?"
   - На странице товара и в каталоге нужно выводить название, рейтинг (рейтинг не выводится)
  - при нажатии "след страница" внизу, то автоматически видно только них страницы (особенность SPA?)
  - возможность видеть, сколько данного товара в наличии (подписать, чтобы понятно было, а не просто число рядом с ценой)
  - возможность на главной странице добавить несколько одинаковых товаров с помощью вписывания кол-ва или потыкать кол-во (щас стремно реализовано)
